languageCode: "en"
title: "larntocode"
baseURL: "https://larntocode.com/"
enableInlineShortcodes: true

params:
  homepage: "https://larntocode.com"
  current_version: 1.5.5
  authors: Mukesh
  social_image_path: /tailwind/images/og-image.png

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: colorful
  tableOfContents:
    startLevel: 2
    endLevel: 6

buildDrafts: true
buildFuture: true

enableRobotsTXT: true
metaDataFormat: "yaml"
disableKinds: ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir: "_gh_pages"
